name: gosec

on:
  - push
  - pull_request

jobs:
  sec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...
